version: "3"
services:
  kademlia_nodes:
    image: kadlab:latest
    stdin_open: true
    tty: true
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
    networks:
      - kademlia_network

networks:
  kademlia_network:
    name: kademlia_network
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
